### Determinants:

1) Help us in mapping a square matrix with a scalar.<br>
2) They determine whether a square matrix can be inverted or not.

#### For a matrix X, determinant of X is denoted by det(X)
* If the determinant of a matrix is 0, it cannot be inverted.
* The matrices having determinant 0 are called singular matrices. Such matrices contain linearly dependent columns.

### 2x2 Matrix Determinants

In [1]:
import numpy as np
import torch

In [2]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [3]:
np.linalg.det(X)

-2.0000000000000004

In [4]:
N = np.array([[-4, 1], [-8, 2]])
N

array([[-4,  1],
       [-8,  2]])

In [5]:
np.linalg.det(N)

0.0

In [6]:
# Uncommenting the following line results in a "singular matrix" error
# Ninv = np.linalg.inv(N)

In [7]:
N = torch.tensor([[-4, 1], [-8, 2.]]) # must use float not int

In [8]:
torch.det(N) 

tensor(0.)

#### For a matrix [[a, b], [c, d]], the determinant is given by ad - bc, let's confirm this with an example.

In [10]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [11]:
round(np.linalg.det(X)) == (-3 * 4) - (-5 * 2)

True