### Determinants:

1) Help us in mapping a square matrix with a scalar.<br>
2) They determine whether a square matrix can be inverted or not.

#### For a matrix X, determinant of X is denoted by det(X)
* If the determinant of a matrix is 0, it cannot be inverted.
* The matrices having determinant 0 are called singular matrices. Such matrices contain linearly dependent columns.

### 2x2 Matrix Determinants

In [2]:
import numpy as np
import torch

In [3]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [4]:
np.linalg.det(X)

-2.0000000000000004

In [5]:
N = np.array([[-4, 1], [-8, 2]])
N

array([[-4,  1],
       [-8,  2]])

In [6]:
np.linalg.det(N)

0.0

In [7]:
# Uncommenting the following line results in a "singular matrix" error
# Ninv = np.linalg.inv(N)

In [8]:
N = torch.tensor([[-4, 1], [-8, 2.]]) # must use float not int

In [9]:
torch.det(N) 

tensor(0.)

#### For a matrix [[a, b], [c, d]], the determinant is given by ad - bc, let's confirm this with an example.

In [10]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [11]:
round(np.linalg.det(X)) == (-3 * 4) - (-5 * 2)

True

### Generalizing Determinants

In [12]:
X = np.array([[1, 2, 4], [2, -1, 3], [0, 5, 1]])
X

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

In [13]:
np.linalg.det(X)

19.999999999999996

In [14]:
round(np.linalg.det(X)) == 1 * ((1 * -1) - (5 * 3)) - 2 * ((1 * 2) - (0 * 3)) + 4 * ((5 * 2) - (0 * -1))

True

#### Similarly determinant of any matrix can be calculated, given the matrix is square.

### Exercises:
1) Determinant of [[25, 2],[3, 4]], and whether it is a singular matrix

In [16]:
X = np.array([[25, 2], [3, 4]])
X

array([[25,  2],
       [ 3,  4]])

In [18]:
det_X = np.linalg.det(X)
det_X

94.0

det(X) is not 0, hence the matrix isn't singular.

In [19]:
X = np.array([[-2, 0], [0, -2]])
X

array([[-2,  0],
       [ 0, -2]])

In [20]:
det_X = np.linalg.det(X)
det_X

4.0

det(X) is not 0, hence the matrix isn't singular.

In [22]:
X = np.array([[2, 1, -3], [4, -5, 2], [0, -1, 3]])
X

array([[ 2,  1, -3],
       [ 4, -5,  2],
       [ 0, -1,  3]])

In [23]:
det_X = np.linalg.det(X)
det_X

-26.000000000000014

det(X) is not 0, hence the matrix isn't singular.