In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

### Matrices (Rank 2 Tensors) in NumPy

In [2]:
# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape # Returns number of rows and columns in a matrix.

(3, 2)

In [4]:
X.size # Returns total number of elements in a matrix.

6

In [5]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [6]:
# Select middle row of matrix X: 
X[1,:]

array([ 5, 26])

In [7]:
# Another slicing-by-index example: 
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices in PyTorch

In [8]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [12]:
X_pt.shape # Same as numpy.

torch.Size([3, 2])

In [16]:
X_pt[1,:] 

tensor([ 5, 26])

### Matrices in TensorFlow

In [17]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [18]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [19]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [20]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>

### Higher-Rank Tensors

As an example, rank 4 tensors are common for images, where each dimension corresponds to: 

1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28 for [MNIST digits](http://yann.lecun.com/exdb/mnist/)
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [21]:
images_pt = torch.zeros([32, 28, 28, 3]) 

# Here all these 4 parameters represent the 4 dimensions in space. The above line of code can be helpful, when training a model 
# of 32 images with fixed height and width and the colours.

In [22]:
images_tf = tf.zeros([32, 28, 28, 3])