In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

#### 1) What is the transpose of the vector ([[25],[2],[-3],[-23]])

In [3]:
X = np.array([[25],[2],[-3],[-23]])
X

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [4]:
X_Transpose = X.T
X_Transpose

array([[ 25,   2,  -3, -23]])

#### 2) What  are the dimensions of [[42,4,7,99],[-99,-3,17,22]]

In [15]:
Y = np.array([[42,4,7,99],[-99,-3,17,22]])
Y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [16]:
Y.shape

(2, 4)

#### 3) What is the position of the element in Y whose value is 17

In [17]:
result = np.where(Y == 17)
result


(array([1], dtype=int64), array([2], dtype=int64))

#### But here the indices start from 0 and in algebraic notation they start from 1, so we will have to add 1 to both the row and the column, thus the position is (1+1, 2+1) i.e. (2,3).